#! /bin/bash

file=$1
IFS=$'\n'
i=0
for var in $(cat $file); do
	((++i))
	echo "$i $var"
done




# i=0
# echo "Argument №0: $0"
# for arg in $* ; do
# 	((++i))
# 	echo "Argument №$i: $arg"
# done

# mydir=$HOME
# if [ -d $mydir ]; then
# 	echo "Yes, directory $mydir exists:"
# 	ls -laF $mydir
# else
# 	echo "Directory $mydir does't exist!"
# fi


# s1="$1"
# s2="$2"
# if [ $s1 \> $s2 ] ; then
# 	echo "string \"$s1\" greater then string \"$s2\""
# else
# 	echo "string \"$s1\" less or equel then string \"$s2\""
# fi


# user="$1"
# if [ $user = $USER ] ; then
# 	echo "The user \"$user\" is the current logged in user"
# fi


# echo "Hello, shell!"
# echo "I am \"$(whoami)\""
# echo "My current folder is \"$(pwd)\""

# val1=$1
# if [ $val1 -gt 5 ] ; then
# 	echo "The test value $val1 is greater then 5"
# else
# 	echo "The test value $val1 is not greater then 5"
# fi
